services:
  - type: web
    name: geo-bangladesh-app
    runtime: python
    buildCommand: pip install -r backend/requirements.txt && python backend/manage.py migrate
    startCommand: gunicorn --chdir backend geo_bangladesh_api.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        value: mongodb+srv://GeoBangladeshApp:<GeoBangladeshApp123>@geobangladeshapp.qty9xmu.mongodb.net/?retryWrites=true&w=majority&appName=GeoBangladeshApp