name: geo_bangladesh
description: A Flutter application for managing geographic entities in Bangladesh.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  flutter_image_compress: ^2.0.4
  geolocator: ^10.1.0
  provider: ^6.0.5
  cached_network_image: ^3.3.0
  path: ^1.8.3
  shared_preferences: ^2.2.0
  permission_handler: ^10.2.0
  sqflite: ^2.3.0
  connectivity_plus: ^5.0.1
  intl: ^0.18.1
  flutter_secure_storage: ^9.0.0
  sqflite_common_ffi_web: ^0.3.5
  http_parser: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
